### ISSUE TITLE
annotate を入れる

### ISSUE THREAD

**Issue by YasuakiNakazawa** [Kodai0913/hyoka.com#1]
[annotate](https://github.com/ctran/annotate_models) を入れる。

models に対して i, k のオプションを指定して annotate を実行する。

**Comment by Kodai0913** [comment]
annotateというgemを使いmodelsに注釈を加えました。iオプションを指定してデータベースのindexを、kオプションを指定して外部キー制限も注釈の中に書かれるようにしました。hotfixブランチで作業が完了しています。確認をよろしくお願いいたします。
