### ISSUE TITLE
レビューの追加をリレーションを意識して実装する

### ISSUE THREAD

**Issue by YasuakiNakazawa** [Kodai0913/hyoka.com#10]
現状、パラメータでやってくる `service_id` を Review の初期化時に設定しているだけで、そのIDに該当するサービスの有効性については見ていない。
また、データの関連を踏まえると

```
service = Service.find(params[:service_id)
review = service.reviews.build(review_params)
if review.save
  ..
...
```
のように、「サービスのレビュー」という文脈を意識できるようにすると良さそう。

**Comment by Kodai0913** [comment]
すみません。理解ができないので解説をよろしくお願いいたします。
・service_idに該当するサービスの有効性とはどういうことでしょうか？

後半のサービスのレビューということをわかりやすくするためにserviceにサービスを代入してからreviewを保存することは理解しました。
