### ISSUE TITLE
DBの文字列のカラムに制約を設ける

### ISSUE THREAD

**Issue by YasuakiNakazawa** [Kodai0913/hyoka.com#2]
設けるべき制約は `limit` 。
参考: https://railsguides.jp/active_record_migrations.html#%E3%82%AB%E3%83%A9%E3%83%A0%E4%BF%AE%E9%A3%BE%E5%AD%90

必要十分な長さプラス余裕を持って設定する。
例えば電話番号や国名などの固有名詞に関しては「一番長いもの」が存在しうるので調べて分かる範囲で適切な文献・情報をもとにして決める。

**Comment by YasuakiNakazawa** [comment]
既存のマイグレーションを更新する場合は事前にダンプを取得するなどすると良さそう。
なかみてないので正しいかわからないけど下記のような記事参考にしてみると良いかも。
https://neos21.net/blog/2020/11/21-03.html
※ DBの形状変更することになるのでダンプはデータのみにしてスキーマはそのままにしておくように。

**Comment by Kodai0913** [comment]
全てのテーブルの全ての文字列のカラムに制約を加えると間違っていた時修正が大変なのでまずUsersテーブルのnameカラムに50文字までという制約を加えました。参考にしたのはTwitterの制約です。Twitterはユーザーネームを現在50文字までと制限しています。
