### ISSUE TITLE
DBのマイグレートに comment オプションを設ける。

### ISSUE THREAD

**Issue by YasuakiNakazawa** [Kodai0913/hyoka.com#3]
下記参考にやってみてほしい。
https://railsguides.jp/active_record_migrations.html#%E3%82%AB%E3%83%A9%E3%83%A0%E4%BF%AE%E9%A3%BE%E5%AD%90

**Comment by Kodai0913** [comment]
全てのテーブルの全てのカラムに追加すると間違っていた場合大変なので、まずはUsersテーブルのnameカラムにのみcommentオプションを追加してみました。確認をよろしくお願いいたします。
